version: '3.7'

services:
  whoami:
    # A container that exposes an API to show its IP address
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blw-whoami.rule=Host(`whoami.local.blw.sh`)"
      - "traefik.http.routers.blw-whoami.tls.certresolver=cloudflare"
      - "traefik.http.routers.blw-whoami.tls=true"
networks:
  default:
    external:
      name: traefik