version: '3.7'

services:
    ide:
        image: codercom/code-server:latest
        labels:
            - "traefik.http.services.nginx-php-ide-ide.loadbalancer.server.port=8080"
            - "traefik.http.routers.nginx-php-ide-ide.rule=Host(`ide.nginx-php.local.blw.sh`)"
            - "traefik.http.routers.nginx-php-ide-ide.tls.certresolver=cloudflare"
            - "traefik.http.routers.nginx-php-ide-ide.tls=true"
            - "traefik.enable=true"
        volumes:
            - ./src:/home/coder/project
        ports:
        - 8081:8080
        networks:
            - traefik
    web:
        restart: always
        image: nginx:latest
        labels:
            - "traefik.http.routers.nginx-php-ide-app.rule=Host(`nginx-php-ide-app.local.blw.sh`)"
            - "traefik.http.routers.nginx-php-ide-app.tls.certresolver=cloudflare"
            - "traefik.http.routers.nginx-php-ide-app.tls=true"
            - "traefik.enable=true"
        expose:
            - 80
        volumes:
            - ./src:/src/:rw,cached
            - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        env_file:
            - ./.env
        links:
            - php
            - db
        networks:
            - traefik
            - internal
    php:
        restart: always
        build: .
        expose:
            - 9000
        volumes:
            - ./src:/src/:rw,cached
            - ./etc/php.ini:/usr/local/etc/php/conf.d/00_base-example.ini:ro
        env_file:
            - ./.env
        depends_on:
            - db
        networks:
            - internal
    db:
        image: mysql:5.6.41
        volumes:
            - db-data:/var/lib/mysql/data
        env_file:
            - ./.env
        networks:
            - internal
volumes:
    db-data:
networks:
    traefik:
        external: true
        name: traefik
    internal:
        name: internal
